### PR TITLE
RedHat 8 support

### PR DESCRIPTION
**Pull request by kbcz1989**
Hi,

role didn't work for me on centos8 so I fixed it. Please review.

BR

### CODE REVIEW

**Comment by tkimball83** [comment]
Thanks for the PR!

I think we should break the package installs into separate tasks per dist or create vars files, versus jinja in a task list loop.

I'll update the branch and have you review.

**Comment by tkimball83** [comment]
I ended up creating a new branch for this, please take a look at:

https://github.com/linuxhq/ansible-role-selinux/tree/el8

If this works for you I'll have it merged.  Thanks!

**Comment by kbcz1989** [comment]
I tried it and it works ok. Thank you!

**Comment by tkimball83** [comment]
Closing this pull request in favor of https://github.com/linuxhq/ansible-role-selinux/pull/3 and created tag v0.0.4.

**Pull request closed without merging**
